global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "housing-microservice"
    static_configs:
      - targets: ["app:8080"] # "app" is the docker-compose service name
